import React,{useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const purposes=['홍보영상','교육영상','공모전영상','브랜드영상','제품·서비스 소개','감성 스토리','행사 스케치','숏폼 콘텐츠'];const styles=['시네마틱','다큐멘터리','광고','감성 브이로그','교육 콘텐츠','SNS 숏폼','스토리텔링','애니메이션'];
async function api(path,body){const r=await fetch('/api/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json()}
function prompt(f){return`당신은 전문 AI 영상 기획자입니다. 다음 조건으로 연속 영상 기획안을 만드세요.\n주제: ${f.topic}\n목적: ${f.purpose}\n길이: ${f.duration}\n비율: ${f.ratio}\n스타일: ${f.style}\n주인공: ${f.character||'주제에 적합한 인물 또는 대상'}\n\n규칙:\n1. 주제에 맞게 새롭게 기획합니다.\n2. 인물이 있으면 CHARACTER BIBLE을 만들고 모든 장면에서 얼굴·나이·헤어·체형·의상·신발·액세서리를 동일하게 유지합니다.\n3. Scene 2부터 이전 장면과 공간·행동·시각적 연속성을 유지합니다.\n4. IMAGE PROMPT와 VIDEO PROMPT를 반드시 분리합니다.\n5. 이미지 프롬프트에는 움직임을 넣지 않습니다.\n6. 영상 프롬프트에는 ACTION, CAMERA MOVEMENT, ENVIRONMENT MOVEMENT, DURATION, CONTINUITY를 포함합니다.\n7. 내레이션과 짧은 화면 자막을 별도로 만듭니다.\n8. 이미지·영상 프롬프트는 영어, 나머지는 한국어로 작성합니다.\n\n출력 순서: 영상 제목 / 한 줄 기획 / 핵심 메시지 / 타깃 / CHARACTER BIBLE / Scene별 목적·화면·행동·감정·카메라·내레이션·자막·IMAGE PROMPT·VIDEO PROMPT.`}
function App(){const[v,setV]=useState('gate'),[code,setCode]=useState(''),[msg,setMsg]=useState(''),[admin,setAdmin]=useState({id:'',password:''}),[settings,setSettings]=useState(null),[f,setF]=useState({topic:'',purpose:'홍보영상',duration:'45초',ratio:'9:16',style:'시네마틱',character:''}),[out,setOut]=useState('');const copy=t=>navigator.clipboard.writeText(t);
async function enter(){setMsg('');if(!/^\d{4}$/.test(code))return setMsg('입장코드는 4자리 숫자입니다.');const d=await api('gate',{code});d.ok?setV('create'):setMsg(d.message)}async function login(){const d=await api('admin-settings',{...admin,action:'get'});if(d.ok){setSettings(d.settings);setV('admin')}else setMsg(d.message)}async function save(){const d=await api('admin-settings',{...admin,action:'save',settings});setMsg(d.ok?'관리자 설정을 저장했습니다.':d.message)}
if(v==='gate')return <main className="gate"><div className="gate-card"><button className="gate-logo" onClick={()=>{setMsg('');setV('login')}}><div className="brand-title">CINEMAG</div></button><div className="eyebrow">AI VIDEO CREATIVE STUDIO</div><h1>영상 제작 설계기</h1><p>프로젝트와 결과물은 저장하지 않습니다.</p><input maxLength="4" inputMode="numeric" placeholder="4자리 입장코드" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><button className="primary" onClick={enter}>시작하기</button>{msg&&<p className="error">{msg}</p>}</div></main>;
if(v==='login')return <main className="gate"><div className="gate-card"><h1>관리자 로그인</h1><input placeholder="관리자 ID" value={admin.id} onChange={e=>setAdmin({...admin,id:e.target.value})}/><input type="password" placeholder="비밀번호" value={admin.password} onChange={e=>setAdmin({...admin,password:e.target.value})}/><button className="primary" onClick={login}>로그인</button><button className="copy-btn" onClick={()=>setV('gate')}>돌아가기</button>{msg&&<p className="error">{msg}</p>}</div></main>;
if(v==='admin')return <main className="gate"><div className="gate-card"><h1>운영 설정</h1><label>입장코드<input maxLength="4" value={settings.accessCode} onChange={e=>setSettings({...settings,accessCode:e.target.value})}/></label><label>강사용 코드<input maxLength="4" value={settings.instructorCode} onChange={e=>setSettings({...settings,instructorCode:e.target.value})}/></label><label>사용 시작일<input type="date" value={settings.startDate} onChange={e=>setSettings({...settings,startDate:e.target.value})}/></label><label>사용 종료일<input type="date" value={settings.endDate} onChange={e=>setSettings({...settings,endDate:e.target.value})}/></label><button className="primary" onClick={save}>설정 저장</button><button className="copy-btn" onClick={()=>setV('gate')}>나가기</button>{msg&&<p className={msg.includes('저장')?'success':'error'}>{msg}</p>}<p>사용자의 영상 주제·기획·프롬프트·결과물은 저장하지 않습니다.</p></div></main>;
return <><header className="appbar"><div><div className="brand-title">CINEMAG</div><div className="brand-sub">NO API · NO PROJECT STORAGE</div></div><button className="copy-btn" onClick={()=>setV('gate')}>나가기</button></header><main className="workspace"><section className="sheet brief"><div className="section-title"><span>VIDEO BRIEF</span><h2>무엇을 만들까요?</h2></div><label className="brief-field"><span>영상 주제</span><textarea value={f.topic} onChange={e=>setF({...f,topic:e.target.value})} placeholder="만들고 싶은 영상의 주제를 입력하세요."/></label><div className="settings-row"><b>영상 목적</b><select value={f.purpose} onChange={e=>setF({...f,purpose:e.target.value})}>{purposes.map(x=><option>{x}</option>)}</select><b>길이</b><select value={f.duration} onChange={e=>setF({...f,duration:e.target.value})}>{['15초','30초','45초','60초'].map(x=><option>{x}</option>)}</select><b>화면 비율</b><select value={f.ratio} onChange={e=>setF({...f,ratio:e.target.value})}>{['9:16','16:9','1:1'].map(x=><option>{x}</option>)}</select><b>스타일</b><select value={f.style} onChange={e=>setF({...f,style:e.target.value})}>{styles.map(x=><option>{x}</option>)}</select><b>주인공 힌트(선택)</b><input value={f.character} onChange={e=>setF({...f,character:e.target.value})} placeholder="예: 40대 한국인 여성 어린이집 교사"/></div><button className="generate" onClick={()=>{if(!f.topic.trim())return setMsg('영상 주제를 입력해주세요.');setOut(prompt(f));setMsg('')}}>AI 기획 프롬프트 만들기 <span>→</span></button>{msg&&<p className="error">{msg}</p>}</section>{out&&<section className="sheet document"><div className="number-title"><span>01</span>완성형 AI 기획 프롬프트</div><p>아래 내용을 ChatGPT 또는 Gemini에 복사해 사용하세요. CINEMAG는 AI API를 호출하지 않습니다.</p><pre className="prompt">{out}</pre><button className="primary" onClick={()=>copy(out)}>전체 프롬프트 복사</button><button className="copy-btn" onClick={()=>{setOut('');setF({...f,topic:'',character:''})}}>처음부터 만들기</button></section>}</main></>}
createRoot(document.getElementById('root')).render(<App/>);
